name: publish-report

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::googlesheets4
            any::quarto
            any::gt

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("import_data.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add survey_data.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

  publish-quarto:
    runs-on: ubuntu-latest
    needs: import-data
    permissions:
        contents: write
        steps:
          - name: Check out repository
            uses: actions/checkout@v3
    
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
    
          - name: Install R
            uses: r-lib/actions/setup-r@v2
            with:
              r-version: '4.2.0'
    
          - uses: r-lib/actions/setup-r-dependencies@v2
            with:
              packages: |
                any::knitr
                any::quarto
                any::gt
    
          - name: Render and Publish
            uses: quarto-dev/quarto-actions/publish@v2
            with:
              target: gh-pages
              path: my_report_quarto
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}